### ISSUE TITLE
Democratic voting

### ISSUE THREAD

**Issue by Hannah-GBS** [cah-98/PlateUp-MorePlayersMod#1]
It'd be super helpful if you could set a percentage of needed players to ready up in the config.

Would also be useful if card voting was democratic (either most popular when all players have voted if its not a tie, or use the same or a new config for how many players need to vote before most popular card is picked).

**Comment by cah-98** [comment]
I will take a look when i have time

**Comment by gdesmott** [comment]
Agreed, I'd also like to have a "tyran mode" when the first player takes all the decision by him/herself (starting game, picking cards, etc). I play only couch gaming and there is always someone grabbing a beer or something when we need to vote.
